/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/BANG BRANDING PALE.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano.geometry}
        material={materials["Material.001"]}
        position={[0.02, -0.06, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano001.geometry}
        material={materials["Material.001"]}
        position={[0.02, -0.06, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002.geometry}
        material={materials["Material.001"]}
        position={[0.02, -0.06, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto.geometry}
        material={materials["Material.001"]}
        position={[-0.21, -0.05, 0.66]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto001.geometry}
        material={materials["Material.001"]}
        position={[-1.03, -0.05, -0.04]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto002.geometry}
        material={materials["Material.001"]}
        position={[0.59, 0.58, 0.42]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PALE001.geometry}
        material={materials.wire_154215229}
        position={[0.02, -0.05, -0.1]}
        scale={[1, 1, 1.25]}
      />
      <group position={[-0.41, 1.19, -0.62]} rotation={[Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD_D2-geom"].geometry}
          material={materials.TQ_ARD_D2_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD_D2-geom_1"].geometry}
          material={materials.TQ_ARD_D2_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD_D2-geom_2"].geometry}
          material={materials.TQ_ARD_D2_edge}
        />
      </group>
      <group position={[-0.46, -0.37, -0.63]} rotation={[Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom"].geometry}
          material={materials.TQ_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom_1"].geometry}
          material={materials.TQ_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom_2"].geometry}
          material={materials.TQ_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/BANG BRANDING PALE.gltf");
